add docstring for `DirichletMultinomial`
JuliaStats/Distributions.jl pull request #1656
Opened 2022-12-30 16:46 UTC by pri1311

Closes #1601 

Latex output image from QuickLatex render:
<img width="391" alt="Screenshot 2022-12-30 at 10 16 22 PM" src="https://user-images.githubusercontent.com/64613009/210093703-979ce7f1-3546-4ede-8d15-5319b83e3557.png">

2022-12-31 04:13 UTC, ParadaCarleton requested changes

2022-12-31 04:13 UTC, ParadaCarleton commented on src/multivariate/dirichletmultinomial.jl
> +can be understood as draws from a Multinomial distribution where each sample has a slightly different probability vector, which is itself drawn from a common Dirichlet distribution. This contrasts wi
```suggestion
is the distribution of a draw from a Multinomial distribution where each sample has a slightly different probability vector,  drawn from a common Dirichlet distribution. 

This contrasts with the Multinomial distribution, which assumes that all observations arise from a single fixed probability vector. This enables the Dirichlet-multinomial to accommodate more variable (a.k.a, over-dispersed) count data than the Multinomial.
```

2022-12-31 04:13 UTC, ParadaCarleton commented on src/multivariate/dirichletmultinomial.jl
> +"""
Docstring is missing a type signature--see [here for examples.](https://github.com/invenia/BlueStyle#documentation)

2022-12-31 08:02 UTC, devmotion commented on src/multivariate/dirichletmultinomial.jl
> +DirichletMultinomial(n::Integer, k::Integer)                       # Dirichlet-Multinomial distribution with n trials and paramemeter vector of length k of ones.
```suggestion

# Let k be a positive integer
DirichletMultinomial(n, k) # Dirichlet-multinomial distribution with n trials and parameter vector of length k of ones.
```

2023-01-06 03:20 UTC, ParadaCarleton approved these changes
Looks good to me! @devmotion any final comments?

2023-01-16 16:27 UTC, merged