Generalize affine distributions to negative scales
JuliaStats/Distributions.jl pull request #1657
Opened 2023-01-07 15:10 UTC by ParadaCarleton

2023-01-07 22:02 UTC, devmotion requested changes

2023-01-07 22:02 UTC, devmotion commented on test/univariate/locationscale.jl
> +    ls_norm = AffineDistribution(1.0, 1, Normal())
Revert, this tests deprecated constructors:
```suggestion
    ls_norm = LocationScale(1.0, 1, Normal())
```

2023-01-07 22:02 UTC, devmotion commented on test/univariate/locationscale.jl
> +    @test ls_norm isa AffineDistribution{Float64, Continuous, Normal{Float64}}
Revert, this checks that changes are non-breaking ans dispatches with `LocationScale` still work correctly:
```suggestion
    @test ls_norm isa LocationScale{Float64, Continuous, Normal{Float64}}
```

2023-01-08 01:55 UTC, ParadaCarleton commented on src/univariate/locationscale.jl
> +entropy(d::ContinuousAffineDistribution) = entropy(d.ρ) + log(abs(d.σ))
Yes, but it returns a tuple `(log(abs(det(x))), sign(x))` rather than just the log of the magnitude.

2023-01-08 11:17 UTC, devmotion commented on src/univariate/locationscale.jl
> +entropy(d::ContinuousAffineDistribution) = entropy(d.ρ) + log(abs(d.σ))
I see 👍

2023-01-08 11:17 UTC, devmotion commented on src/univariate/locationscale.jl
> +gradlogpdf(d::ContinuousAffineDistribution, x::Real) =
```suggestion
cf(d::AffineDistribution, t::Real) = cf(d.ρ,t*d.σ) * exp(1im*t*d.μ)
gradlogpdf(d::ContinuousAffineDistribution, x::Real) = gradlogpdf(d.ρ,(x-d.μ)/d.σ) / d.σ
```

2023-01-08 11:17 UTC, devmotion commented on src/univariate/locationscale.jl
> +    gradlogpdf(d.ρ, (x-d.μ)/d.σ) / d.σ
```suggestion
```

2023-01-10 08:29 UTC, devmotion requested changes

2023-01-10 08:29 UTC, devmotion commented on src/univariate/locationscale.jl
> +for (f, fc) in zip(CDF_FNS, reverse(CDF_FNS))
```suggestion
for (f, fc) in ((:cdf, :ccdf), (:ccdf, :cdf), (:logcdf, :logccdf), (:logccdf, :logcdf))
```

2023-01-10 08:29 UTC, devmotion commented on src/univariate/locationscale.jl
> +    x = (x - d.μ) / d.σ
The new `x` is something else, possibly even of a different type. It's confusing to use the same name.
```suggestion
    z = (x - d.μ) / d.σ
```

2023-01-10 08:29 UTC, devmotion commented on src/univariate/locationscale.jl
> +    return d.σ > 0 ? cdf(d.ρ, x) : (ccdf(d.ρ, x) + pdf(d.ρ, x))
```suggestion
    return d.σ > 0 ? cdf(d.ρ, z) : (ccdf(d.ρ, z) + pdf(d.ρ, z))
```

2023-01-10 08:29 UTC, devmotion commented on src/univariate/locationscale.jl
> +ccdf(d::DiscreteAffineDistribution, x::Real) = 1 - cdf(d, x)
This is different from the current definitions - currently we do not use the default 1 - cdf.
```suggestion
function ccdf(d::DiscreteAffineDistribution, x::Real)
    z = (x - d.μ) / d.σ
    # Have to exlude probability mass at endpoints
    return d.σ > 0 ? ccdf(d.ρ, z) : (cdf(d.ρ, z) - pdf(d.ρ, x))
end
```

2023-01-10 08:29 UTC, devmotion commented on src/univariate/locationscale.jl
> +logcdf(d::DiscreteAffineDistribution, x::Real) = log(cdf(d, x))
Also here the point is to not use this default.

2023-01-10 08:29 UTC, devmotion commented on src/univariate/locationscale.jl
> +logccdf(d::DiscreteAffineDistribution, x::Real) = log(ccdf(d, x))
Same here, do not use thia default fallback.

2023-01-10 12:09 UTC, devmotion commented on src/univariate/locationscale.jl
> +logcdf(d::DiscreteAffineDistribution, x::Real) = log(cdf(d, x))
```suggestion
function logcdf(d::DiscreteAffineDistribution, x::Real)
    z = (x - d.μ) / d.σ
    return d.σ > 0 ? logcdf(d.ρ, z) : logaddexp(logccdf(d.ρ, z), logpdf(d.ρ, z))
```

2023-01-10 12:11 UTC, devmotion commented on src/univariate/locationscale.jl
> +logccdf(d::DiscreteAffineDistribution, x::Real) = log(ccdf(d, x))
```suggestion
function logccdf(d::DiscreteAffineDistribution, x::Real)
    z = (x - d.μ) / d.σ
    return d.σ > 0 ? logccdf(d.ρ, z) : logsubexp(logcdf(d.ρ, z), logpdf(d.ρ, z))
end
```

2023-01-10 12:12 UTC, devmotion commented on src/univariate/locationscale.jl
> +        return d.σ > 0 ? $f(d.ρ, x) : $fc(d.ρ, x)
```suggestion
        z = (x - d.μ) / d.σ
        return d.σ > 0 ? $f(d.ρ, z) : $fc(d.ρ, z)
```

2023-01-10 12:14 UTC, devmotion commented on test/univariate/locationscale.jl
> +    ls_norm = LocationScale(1.0, 1, Normal())
```suggestion
    @test_deprecated ls_norm = LocationScale(1.0, 1, Normal())
```

2023-01-10 12:16 UTC, devmotion commented on src/univariate/locationscale.jl
> +AffineDistribution(μ::Real, σ::Real, d::AffineDistribution) = AffineDistribution(μ + σ * d.μ, σ * d.σ, d.ρ)
```suggestion
AffineDistribution(μ::Real, σ::Real, d::AffineDistribution) = AffineDistribution(μ + d.μ * σ, σ * d.σ, d.ρ)
```

2023-01-10 12:28 UTC, devmotion commented
I applied some of the suggestions (mostly to remove unrelated changes) to speed up the review process since I think the generalization would be quite useful.

2023-01-10 13:15 UTC, ParadaCarleton commented
Looks good to me!

2023-01-10 20:20 UTC, ParadaCarleton commented
> I applied some of the suggestions (mostly to remove unrelated changes) to speed up the review process since I think the generalization would be quite useful.

Anything missing, or should I merge this?

2023-01-10 20:32 UTC, devmotion commented
> Anything missing, or should I merge this?

No, please do not merge. Tests do not pass.

2023-01-12 02:22 UTC, ParadaCarleton commented
> > Anything missing, or should I merge this?
> 
> No, please do not merge. Tests do not pass.

Right, thanks, I missed that (since tests on 1.3 were passing, and tests passed locally). Looks like in some versions/hardware there's a tiny bit of floating-point error that was causing trouble with tests that didn't have `atol` set. That's been corrected now.

2023-01-12 13:03 UTC, devmotion approved these changes
Looks good to me!

2023-01-12 15:32 UTC, merged