add loglogistic distribution
JuliaStats/Distributions.jl pull request #1780
Opened 2023-09-19 20:05 UTC by yunzli

This PR adds [log-logistic](https://en.wikipedia.org/wiki/Log-logistic_distribution) distribution to the package. 

The log-logistic distribution has two parameters: scale and shape. It has been widely used in survival analysis.

The model implementation is in `src/univariate/continuous/loglogistic.jl`
The test is in `test/univariate/continuous/loglogistic.jl`

2023-09-22 01:53 UTC, ParadaCarleton commented
This looks like a pretty solid implementation, but I do wonder if we should be adding Log* distributions piecemeal like this, rather than providing a more general interface for transformed variables.

2023-09-23 05:53 UTC, ParadaCarleton requested changes

2023-09-23 08:31 UTC, devmotion reviewed
Thank you for the PR!

I haven't checked the math yet but commented on a few Julia issues that we should fix before merging the PR.

It's good that you added tests! We already have quite extensive automatic tests for distributions but that requires that you add reference values using R to test/refs. Can you fix that?

2023-09-23 08:31 UTC, devmotion commented on src/univariate/continuous/loglogistic.jl
> +        return 0.0
Same here (as a general comment, usually you should avoid Float64 literals).

2023-09-23 08:31 UTC, devmotion commented on src/univariate/continuous/loglogistic.jl
> +		erros("var is defined only when ϕ > 2")
Same here.

2023-09-23 08:31 UTC, devmotion commented on src/univariate/continuous/loglogistic.jl
> +        -Inf
I guess it was supposed to be
```julia
        return -Inf
```
But that would again create a type instability.

2023-09-23 08:31 UTC, devmotion commented on src/univariate/continuous/loglogistic.jl
> +        return 1
Same here.

2023-09-23 08:31 UTC, devmotion commented on src/univariate/continuous/loglogistic.jl
> +        return 0.0
Same here.

2026-07-27 10:52 UTC, devmotion commented
Fixed by #2008

2026-07-27 10:52 UTC, closed without merging